# A2-S2.7 build-only transform: preserve official UQ when available, otherwise use a custom 77% MaxQuality mode.
# Input must already be generated by A2-S2.6.
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$GeneratedRoot
)
$ErrorActionPreference = 'Stop'

function Replace-ExactOnce([string]$Text, [string]$Old, [string]$New, [string]$Label) {
    $count = 0; $pos = 0
    while (($i = $Text.IndexOf($Old, $pos, [StringComparison]::Ordinal)) -ge 0) { $count++; $pos = $i + $Old.Length }
    if ($count -ne 1) { throw "A2-S2.7 ${Label}: expected exactly one source match, found $count" }
    return $Text.Replace($Old, $New)
}

$vkPath = Join-Path $GeneratedRoot 'm3k_vk.h'
if (-not (Test-Path -LiteralPath $vkPath)) { throw "Missing generated m3k_vk.h under $GeneratedRoot" }
$vk = [IO.File]::ReadAllText($vkPath)

$vk = Replace-ExactOnce $vk 'case 1: return "Ultra Quality";' 'case 1: return "Custom Ultra Quality (77%)";' 'profile label'
$vk = Replace-ExactOnce $vk `
    'M3K-UQ: NGX query succeeded but returned 0x0 for %ux%u; using EXPERIMENTAL 77%% true-render fallback %ux%u, then attempting real UltraQuality feature creation' `
    'M3K-UQ-CUSTOM: official UQ query returned 0x0 for %ux%u; using 77%% true-render %ux%u and a supported MaxQuality feature' `
    'fallback log'

$selectStart = $vk.IndexOf('static bool M3kSelectRequestedSrQuality(', [StringComparison]::Ordinal)
$selectEnd = $vk.IndexOf('static bool M3kSwapToSrFeature(', $selectStart, [StringComparison]::Ordinal)
if ($selectStart -lt 0 -or $selectEnd -le $selectStart) { throw 'A2-S2.7 could not locate SR quality selector' }

$selectNew = @'
static bool M3kSelectRequestedSrQuality(UINT profile, UINT renderW, UINT renderH, UINT targetW, UINT targetH)
{
    if (profile < 1 || profile > 5) return false;
    struct Choice { NVSDK_NGX_PerfQuality_Value q; const char *name; const char *hint; };
    static const Choice choices[5] = {
        { NVSDK_NGX_PerfQuality_Value_UltraQuality,     "Ultra Quality",     NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_UltraQuality },
        { NVSDK_NGX_PerfQuality_Value_MaxQuality,       "Quality",           NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Quality },
        { NVSDK_NGX_PerfQuality_Value_Balanced,         "Balanced",          NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Balanced },
        { NVSDK_NGX_PerfQuality_Value_MaxPerf,          "Performance",       NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Performance },
        { NVSDK_NGX_PerfQuality_Value_UltraPerformance, "Ultra Performance", NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_UltraPerformance },
    };
    const Choice &c = choices[profile - 1];

    NVSDK_NGX_Parameter *caps = nullptr;
    const NVSDK_NGX_Result cr = NVSDK_NGX_D3D12_GetCapabilityParameters(&caps);
    if (NVSDK_NGX_FAILED(cr) || caps == nullptr) {
        Log("M3K-SR-LIVE: %s unavailable: GetCapabilityParameters failed 0x%08X", c.name, cr);
        return false;
    }

    // S2.6 hardware proof showed that the official UltraQuality enum returns 0x0 sizing
    // and rejects feature creation on this runtime. Keep the official path when available,
    // but when the sizing fallback is active, create a supported MaxQuality feature at the
    // higher 77% true-render resolution instead.
    if (profile == 1 && g_m3kUqFallbackActive)
    {
        unsigned optW = 0, optH = 0, maxW = 0, maxH = 0, minW = 0, minH = 0;
        float sharp = 0.0f;
        const NVSDK_NGX_Result qr = NGX_DLSS_GET_OPTIMAL_SETTINGS(
            caps, targetW, targetH, NVSDK_NGX_PerfQuality_Value_MaxQuality,
            &optW, &optH, &maxW, &maxH, &minW, &minH, &sharp);
        if (NVSDK_NGX_FAILED(qr) || !optW || !optH) {
            Log("M3K-UQ-CUSTOM: MaxQuality capability query failed at %ux%u result=0x%08X", targetW, targetH, qr);
            return false;
        }
        const bool inRange = renderW >= minW && renderW <= maxW && renderH >= minH && renderH <= maxH;
        Log("M3K-UQ-CUSTOM: 77%% true-source=%ux%u; MaxQuality optimal=%ux%u allowed=%ux%u..%ux%u %s",
            renderW, renderH, optW, optH, minW, minH, maxW, maxH, inRange ? "ACCEPTED" : "OUT-OF-RANGE");
        if (!inRange) return false;

        g.sr_quality = static_cast<int>(NVSDK_NGX_PerfQuality_Value_MaxQuality);
        g.sr_quality_name = "Custom Ultra Quality (77%)";
        g.sr_quality_hint = NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Quality;
        Log("M3K-UQ-CUSTOM: creating supported MaxQuality DLSS feature at %ux%u -> %ux%u", renderW, renderH, targetW, targetH);
        return true;
    }

    unsigned optW = 0, optH = 0, maxW = 0, maxH = 0, minW = 0, minH = 0;
    float sharp = 0.0f;
    const NVSDK_NGX_Result qr = NGX_DLSS_GET_OPTIMAL_SETTINGS(caps, targetW, targetH, c.q,
        &optW, &optH, &maxW, &maxH, &minW, &minH, &sharp);
    if (NVSDK_NGX_FAILED(qr) || !optW || !optH) {
        Log("M3K-SR-LIVE: %s not offered at %ux%u (0x%08X)", c.name, targetW, targetH, qr);
        return false;
    }

    const bool inRange = renderW >= minW && renderW <= maxW && renderH >= minH && renderH <= maxH;
    Log("M3K-SR-LIVE: %s target=%ux%u optimal=%ux%u allowed=%ux%u..%ux%u true-source=%ux%u %s",
        c.name, targetW, targetH, optW, optH, minW, minH, maxW, maxH, renderW, renderH,
        inRange ? "ACCEPTED" : "OUT-OF-RANGE");
    if (!inRange) return false;

    g.sr_quality = static_cast<int>(c.q);
    g.sr_quality_name = c.name;
    g.sr_quality_hint = c.hint;
    return true;
}

'@
$vk = $vk.Substring(0, $selectStart) + $selectNew + $vk.Substring($selectEnd)

[IO.File]::WriteAllText($vkPath, $vk, [Text.UTF8Encoding]::new($false))

$verify = [IO.File]::ReadAllText($vkPath)
foreach ($marker in @(
    'Custom Ultra Quality (77%)',
    'M3K-UQ-CUSTOM: official UQ query returned 0x0',
    'M3K-UQ-CUSTOM: creating supported MaxQuality DLSS feature',
    'NVSDK_NGX_PerfQuality_Value_MaxQuality',
    'NVSDK_NGX_PerfQuality_Value_UltraQuality')) {
    if ($verify.IndexOf($marker, [StringComparison]::Ordinal) -lt 0) {
        throw "A2-S2.7 generated source missing marker: $marker"
    }
}

Write-Host 'A2-S2.7 custom UQ transform applied.'
