# A2-S2.4 build-only transform: keep live 1..5 NR and add live DLSS reconstruction profiles.
# Input must already be generated by A2-S2.3.
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$GeneratedRoot,
    [Parameter(Mandatory=$true)][string]$FeederSource
)

$ErrorActionPreference = 'Stop'

function Replace-ExactOnce([string]$Text, [string]$Old, [string]$New, [string]$Label) {
    $count = 0
    $pos = 0
    while (($i = $Text.IndexOf($Old, $pos, [StringComparison]::Ordinal)) -ge 0) {
        $count++
        $pos = $i + $Old.Length
    }
    if ($count -ne 1) { throw "A2-S2.4 ${Label}: expected exactly one source match, found $count" }
    return $Text.Replace($Old, $New)
}

$vkPath = Join-Path $GeneratedRoot 'm3k_vk.h'
if (-not (Test-Path -LiteralPath $vkPath)) { throw "Missing generated m3k_vk.h under $GeneratedRoot" }
if (-not (Test-Path -LiteralPath $FeederSource)) { throw "Missing Feeder source: $FeederSource" }

$vk = [IO.File]::ReadAllText($vkPath)
$feed = [IO.File]::ReadAllText($FeederSource)

$stateAnchor = 'static UINT M3kRequestedNrPasses() { return g_m3kNrPasses; }'
$stateNew = @'
static UINT g_m3kSrProfileRequested = 2; // Quality
static UINT g_m3kSrProfileApplied = 0xFFFFFFFFu;

static const char *M3kSrProfileName(UINT profile)
{
    switch (profile) {
        case 0: return "DLAA only (presenter)";
        case 1: return "Ultra Quality";
        case 2: return "Quality";
        case 3: return "Balanced";
        case 4: return "Performance";
        case 5: return "Ultra Performance";
        default: return "Unknown";
    }
}

static void M3kWriteSrProfileIni(UINT profile)
{
    wchar_t path[MAX_PATH] = {};
    if (!GetModuleFileNameW(g_self, path, MAX_PATH)) return;
    if (wchar_t *slash = wcsrchr(path, L'\\')) {
        *(slash + 1) = 0;
        wcscat_s(path, L"m3k-nr.ini");
        wchar_t value[8] = {};
        _snwprintf_s(value, _TRUNCATE, L"%u", profile);
        WritePrivateProfileStringW(L"M3K", L"SRProfile", value, path);
    }
}

static UINT M3kRequestedSrProfile() { return g_m3kSrProfileRequested; }
static UINT M3kAppliedSrProfile() { return g_m3kSrProfileApplied; }

static void M3kRequestSrProfileLive(UINT profile)
{
    if (profile > 5) profile = 2;
    if (profile == g_m3kSrProfileRequested) return;
    const UINT old = g_m3kSrProfileRequested;
    g_m3kSrProfileRequested = profile;
#if defined(VK_VERSION_1_0)
    g_m3kSrLatchedFail = false;
    g_m3kSrNeedsReset = true;
#endif
    g_m3k.ResetHistory();
    M3kWriteSrProfileIni(profile);
    Log("M3K-SR-LIVE: ReShade requested reconstruction %s -> %s; applies on next frame",
        M3kSrProfileName(old), M3kSrProfileName(profile));
}

static UINT M3kRequestedNrPasses() { return g_m3kNrPasses; }
'@
$vk = Replace-ExactOnce $vk $stateAnchor $stateNew 'SR profile state/API'

$pollAnchor = '        const UINT nrPasses = requestedPasses < 1 ? 1 : (requestedPasses > 5 ? 5 : requestedPasses);'
$pollNew = @'
        const UINT nrPasses = requestedPasses < 1 ? 1 : (requestedPasses > 5 ? 5 : requestedPasses);
        const UINT requestedSrProfile = GetPrivateProfileIntW(L"M3K", L"SRProfile", 2, path);
        const UINT srProfile = requestedSrProfile <= 5 ? requestedSrProfile : 2;
        static bool srProfileFirst = true;
        if (srProfileFirst || srProfile != g_m3kSrProfileRequested) {
            Log("M3K-SR-LIVE: SRProfile=%u (%s)", srProfile, M3kSrProfileName(srProfile));
            g_m3kSrProfileRequested = srProfile;
#if defined(VK_VERSION_1_0)
            g_m3kSrLatchedFail = false;
            g_m3kSrNeedsReset = true;
#endif
            g_m3k.ResetHistory();
            srProfileFirst = false;
        }
'@
$vk = Replace-ExactOnce $vk $pollAnchor $pollNew 'SRProfile INI poll'

$swapStart = $vk.IndexOf('static bool M3kSwapToSrFeature(', [StringComparison]::Ordinal)
$swapEnd = $vk.IndexOf('static bool M3kRestoreDlaaFeature()', $swapStart, [StringComparison]::Ordinal)
if ($swapStart -lt 0 -or $swapEnd -le $swapStart) { throw 'A2-S2.4 could not locate M3kSwapToSrFeature boundaries' }

$swapNew = @'
static bool M3kSelectRequestedSrQuality(UINT profile, UINT renderW, UINT renderH, UINT targetW, UINT targetH)
{
    if (profile < 1 || profile > 5) return false;
    struct Choice { NVSDK_NGX_PerfQuality_Value q; const char *name; const char *hint; };
    static const Choice choices[5] = {
        { NVSDK_NGX_PerfQuality_Value_UltraQuality,     "Ultra Quality",     NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_UltraQuality },
        { NVSDK_NGX_PerfQuality_Value_MaxQuality,       "Quality",           NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Quality },
        { NVSDK_NGX_PerfQuality_Value_Balanced,         "Balanced",          NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Balanced },
        { NVSDK_NGX_PerfQuality_Value_MaxPerf,          "Performance",       NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Performance },
        { NVSDK_NGX_PerfQuality_Value_UltraPerformance, "Ultra Performance", NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_UltraPerformance },
    };
    const Choice &c = choices[profile - 1];

    NVSDK_NGX_Parameter *caps = nullptr;
    const NVSDK_NGX_Result cr = NVSDK_NGX_D3D12_GetCapabilityParameters(&caps);
    if (NVSDK_NGX_FAILED(cr) || caps == nullptr) {
        Log("M3K-SR-LIVE: %s unavailable: GetCapabilityParameters failed 0x%08X", c.name, cr);
        return false;
    }

    unsigned optW = 0, optH = 0, maxW = 0, maxH = 0, minW = 0, minH = 0;
    float sharp = 0.0f;
    const NVSDK_NGX_Result qr = NGX_DLSS_GET_OPTIMAL_SETTINGS(caps, targetW, targetH, c.q,
        &optW, &optH, &maxW, &maxH, &minW, &minH, &sharp);
    if (NVSDK_NGX_FAILED(qr) || optW == 0 || optH == 0) {
        Log("M3K-SR-LIVE: %s not offered at %ux%u (0x%08X)", c.name, targetW, targetH, qr);
        return false;
    }

    const bool inRange = renderW >= minW && renderW <= maxW && renderH >= minH && renderH <= maxH;
    Log("M3K-SR-LIVE: %s target=%ux%u optimal=%ux%u allowed=%ux%u..%ux%u fixed-source=%ux%u %s",
        c.name, targetW, targetH, optW, optH, minW, minH, maxW, maxH, renderW, renderH,
        inRange ? "ACCEPTED" : "OUT-OF-RANGE");
    if (!inRange) return false;

    g.sr_quality = static_cast<int>(c.q);
    g.sr_quality_name = c.name;
    g.sr_quality_hint = c.hint;
    return true;
}

static bool M3kSwapToSrFeature(UINT renderW, UINT renderH, UINT targetW, UINT targetH)
{
    if (!g.ngx_inited || g.feature == nullptr || g.dev12 == nullptr || g.queue == nullptr)
        return false;

    const int oldQuality = g.sr_quality;
    const char *oldQualityName = g.sr_quality_name;
    const char *oldQualityHint = g.sr_quality_hint;
    if (!M3kSelectRequestedSrQuality(g_m3kSrProfileRequested, renderW, renderH, targetW, targetH))
        return false;

    NVSDK_NGX_Handle *old = g.feature;
    const bool oldSrActive = g.sr_active;
    const bool oldSrRequested = g.sr_requested;
    const UINT oldOutW = g.output_width, oldOutH = g.output_height;

    g.feature = nullptr;
    g.sr_requested = true;
    g.sr_active = true;
    g.output_width = targetW;
    g.output_height = targetH;

    const bool inverted = g_cfg.depth_inverted >= 0 ? g_cfg.depth_inverted != 0 : g.depth_reversed;
    bool crashed = false;
    const bool ok = CreateDlssFeature(renderW, renderH, inverted, &crashed);
    if (!ok)
    {
        if (g.feature != nullptr && g.feature != old)
            SafeReleaseFeature(g.feature);
        g.feature = old;
        g.sr_active = oldSrActive;
        g.sr_requested = oldSrRequested;
        g.output_width = oldOutW;
        g.output_height = oldOutH;
        g.sr_quality = oldQuality;
        g.sr_quality_name = oldQualityName;
        g.sr_quality_hint = oldQualityHint;
        g.frame_ready = true;
        g.warmup_done = true;
        Log("M3K-SR-LIVE: %s feature create %s; keeping currently applied reconstruction",
            M3kSrProfileName(g_m3kSrProfileRequested), crashed ? "crashed (caught)" : "failed");
        return false;
    }

    DrainGpu();
    SafeReleaseFeature(old);
    g.warmup_done = true;
    g.need_reset = true;
    g_m3kSrFeatureActive = true;
    g_m3kSrNeedsReset = true;
    g_m3kSrW = renderW; g_m3kSrH = renderH;
    g_m3kSrOutW = targetW; g_m3kSrOutH = targetH;
    g_m3kSrProfileApplied = g_m3kSrProfileRequested;
    Log("M3K-SR-LIVE: ACTIVE %s %ux%u -> %ux%u (true DXVK source; current jitter path preserved)",
        M3kSrProfileName(g_m3kSrProfileApplied), renderW, renderH, targetW, targetH);
    return true;
}

'@
$vk = $vk.Substring(0, $swapStart) + $swapNew + $vk.Substring($swapEnd)

$restoreAnchor = @'
    g_m3kSrW = g_m3kSrH = g_m3kSrOutW = g_m3kSrOutH = 0;
    Log("M3K-A2-S1: restored baseline %ux%u DLAA", g.width, g.height);
'@
$restoreNew = @'
    g_m3kSrW = g_m3kSrH = g_m3kSrOutW = g_m3kSrOutH = 0;
    g_m3kSrProfileApplied = 0;
    Log("M3K-SR-LIVE: ACTIVE DLAA only on presenter image %ux%u", g.width, g.height);
'@
$vk = Replace-ExactOnce $vk $restoreAnchor $restoreNew 'DLAA applied state'

$updateStart = $vk.IndexOf('static void M3kSrUpdate()', [StringComparison]::Ordinal)
$updateEnd = $vk.IndexOf('// Called while ReShade still has the final MV/depth resources parked as copy_source.', $updateStart, [StringComparison]::Ordinal)
if ($updateStart -lt 0 -or $updateEnd -le $updateStart) { throw 'A2-S2.4 could not locate M3kSrUpdate boundaries' }

$updateNew = @'
static void M3kSrUpdate()
{
    if (g_m3kSrFeatureActive && !g.sr_active)
    {
        g_m3kSrFeatureActive = false;
        g_m3kSrNeedsReset = true;
        g_m3kSrW = g_m3kSrH = g_m3kSrOutW = g_m3kSrOutH = 0;
        g_m3kSrProfileApplied = 0xFFFFFFFFu;
        Log("M3K-SR-LIVE: Feeder rebuilt the feature; reconstruction state will be re-established");
    }

    if (!g_m3kSrRequested || !g_m3kSourceTapReady || g_m3kSourceProof)
    {
        if (g_m3kSrFeatureActive) M3kRestoreDlaaFeature();
        return;
    }

    if (g_m3kSrProfileRequested == 0)
    {
        if (g_m3kSrFeatureActive) M3kRestoreDlaaFeature();
        else g_m3kSrProfileApplied = 0;
        return;
    }

    if (g_m3kSrLatchedFail) return;

    const auto &info = g_m3kPresentSource;
    const bool split = info.presenterWidth == g.width && info.presenterHeight == g.height &&
                       info.width < info.presenterWidth && info.height < info.presenterHeight;
    if (!split)
    {
        if (g_m3kSrFeatureActive) M3kRestoreDlaaFeature();
        return;
    }

    if (g_m3kMode == 1) return;
    if (g_cfg.mode != 2 || g_cfg.passthrough || !g.frame_ready) return;

    if (!M3kBgra8SourceCompatible())
    {
        static bool saidFmt = false;
        if (!saidFmt) {
            saidFmt = true;
            Log("M3K-SR-LIVE: blocked: source VkFormat=%u / Feeder color format=%u",
                info.format, static_cast<UINT>(g.color_fmt));
        }
        return;
    }
    if (info.device != FeedVkValue(g.vk.dev))
    {
        static bool saidDev = false;
        if (!saidDev) { saidDev = true; Log("M3K-SR-LIVE: blocked: source and Feeder VkDevice differ"); }
        return;
    }

    const bool sameDims = g_m3kSrFeatureActive &&
        g_m3kSrW == info.width && g_m3kSrH == info.height &&
        g_m3kSrOutW == info.presenterWidth && g_m3kSrOutH == info.presenterHeight;

    if (sameDims && g_m3kSrProfileApplied == g_m3kSrProfileRequested) return;

    if (sameDims)
    {
        const UINT wanted = g_m3kSrProfileRequested;
        if (!M3kSwapToSrFeature(info.width, info.height, info.presenterWidth, info.presenterHeight))
        {
            Log("M3K-SR-LIVE: requested %s rejected; keeping %s",
                M3kSrProfileName(wanted), M3kSrProfileName(g_m3kSrProfileApplied));
            g_m3kSrProfileRequested = g_m3kSrProfileApplied;
            M3kWriteSrProfileIni(g_m3kSrProfileRequested);
        }
        return;
    }

    if (g_m3kSrFeatureActive && !M3kRestoreDlaaFeature()) return;

    if (!M3kSwapToSrFeature(info.width, info.height, info.presenterWidth, info.presenterHeight))
    {
        g_m3kSrLatchedFail = true;
        Log("M3K-SR-LIVE: initial SR create failed; toggle SRProfile or SRProof to retry");
    }
}

'@
$vk = $vk.Substring(0, $updateStart) + $updateNew + $vk.Substring($updateEnd)

$prepareAnchor = @'
#if defined(VK_VERSION_1_0)
    M3kSrUpdate();
#endif

    g_m3kArmed = false;
'@
$prepareNew = @'
#if defined(VK_VERSION_1_0)
    M3kSrUpdate();
#endif

    g_m3kArmed = false;
#if defined(VK_VERSION_1_0)
    if (g_m3kSrProfileRequested == 0) return;
#endif
'@
$vk = Replace-ExactOnce $vk $prepareAnchor $prepareNew 'DLAA NR bypass'

# Insert after one unique sentence instead of matching its surrounding newlines/Separator.
$overlaySentence = '        ImGui::TextWrapped("First use of a higher count may hitch briefly while its independent NR feature is created. Click 5 once to warm all five, then 1-5 comparisons are immediate without restarting GTA.");'
$overlayReplacement = @'
        ImGui::TextWrapped("First use of a higher count may hitch briefly while its independent NR feature is created. Click 5 once to warm all five, then 1-5 comparisons are immediate without restarting GTA.");

        ImGui::Spacing();
        ImGui::TextUnformatted("DLSS reconstruction (live)");
        int srProfile = static_cast<int>(M3kRequestedSrProfile());
        const char *srItems = "DLAA only (presenter)\0Ultra Quality\0Quality\0Balanced\0Performance\0Ultra Performance\0\0";
        if (ImGui::Combo("Mode##M3KSRProfile", &srProfile, srItems))
            M3kRequestSrProfileLive(static_cast<UINT>(srProfile));
        ImGui::Text("Applied: %s", M3kSrProfileName(M3kAppliedSrProfile()));
        if (M3kRequestedSrProfile() == 0)
            ImGui::TextWrapped("DLAA-only is a presenter-space A/B baseline. GTA's true S1B render remains 1600x900; it is not native-rendered 1440p DLAA.");
        else
            ImGui::TextWrapped("SR profiles keep the true DXVK source resolution fixed and change NVIDIA's DLSS perf-quality profile. Unsupported profiles at this input size are rejected safely.");
'@
$feed = Replace-ExactOnce $feed $overlaySentence $overlayReplacement 'ReShade SR profile controls'

[IO.File]::WriteAllText($vkPath, $vk, (New-Object Text.UTF8Encoding($false)))
[IO.File]::WriteAllText($FeederSource, $feed, (New-Object Text.UTF8Encoding($false)))

$verify = [IO.File]::ReadAllText($vkPath) + [IO.File]::ReadAllText($FeederSource)
foreach ($marker in @(
    'M3K-SR-LIVE: ACTIVE',
    'M3kRequestSrProfileLive',
    'SRProfile',
    'DLAA only (presenter)',
    'Ultra Quality',
    'Ultra Performance',
    'DLSS reconstruction (live)')) {
    if ($verify.IndexOf($marker, [StringComparison]::Ordinal) -lt 0) {
        throw "A2-S2.4 verification marker missing: $marker"
    }
}

Write-Host "A2-S2.4 live SR-profile source ready: $GeneratedRoot"
Write-Host 'ReShade M3K panel now contains permanent NR 1..5 + DLSS reconstruction selector.'
