# A2-S2.6 build-only transform: preserve Feature18 in native DLAA mode and
# make Ultra Quality testable when NGX reports success but no optimal dimensions.
# Input must already be generated by A2-S2.5.
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$GeneratedRoot,
    [Parameter(Mandatory=$true)][string]$FeederSource
)

$ErrorActionPreference = 'Stop'

function Replace-ExactOnce([string]$Text, [string]$Old, [string]$New, [string]$Label) {
    $count = 0
    $pos = 0
    while (($i = $Text.IndexOf($Old, $pos, [StringComparison]::Ordinal)) -ge 0) {
        $count++
        $pos = $i + $Old.Length
    }
    if ($count -ne 1) { throw "A2-S2.6 ${Label}: expected exactly one source match, found $count" }
    return $Text.Replace($Old, $New)
}

$vkPath = Join-Path $GeneratedRoot 'm3k_vk.h'
if (-not (Test-Path -LiteralPath $vkPath)) { throw "Missing generated m3k_vk.h under $GeneratedRoot" }
if (-not (Test-Path -LiteralPath $FeederSource)) { throw "Missing Feeder source: $FeederSource" }

$vk = [IO.File]::ReadAllText($vkPath)
$feed = [IO.File]::ReadAllText($FeederSource)

# Extra state is deliberately small: UQ fallback status for truthful UI/logging,
# plus a stable profile to return to if the real UltraQuality feature rejects the
# experimental input size after GTA has already resized.
$stateOld = @'
static bool g_m3kResolutionConfirmedLogged = false;
'@
$stateNew = @'
static bool g_m3kResolutionConfirmedLogged = false;
static bool g_m3kUqFallbackActive = false;
static UINT g_m3kSrRollbackProfile = 2; // Quality is the safe startup fallback.
'@
$vk = Replace-ExactOnce $vk $stateOld $stateNew 'S2.6 state'

$vk = Replace-ExactOnce $vk `
    'case 0: return "DLAA native";' `
    'case 0: return "Native + NR + DLAA";' `
    'native profile name'

# Remember the currently stable mode before a live request. Reset NR history now;
# when native mode becomes active the existing A1 path will also reset DLAA on the
# first NR-fed frame because g_m3kWasUsed is cleared here.
$requestOld = @'
    const UINT old = g_m3kSrProfileRequested;
    g_m3kSrProfileRequested = profile;
    g_m3kResolutionPlanProfile = 0xFFFFFFFFu;
    g_m3kResolutionPlanOutW = g_m3kResolutionPlanOutH = 0;
    g_m3kResolutionConfirmedLogged = false;
'@
$requestNew = @'
    const UINT old = g_m3kSrProfileRequested;
    if (g_m3kSrProfileApplied <= 5 && g_m3kSrProfileApplied != profile)
        g_m3kSrRollbackProfile = g_m3kSrProfileApplied;
    else if (old <= 5 && old != profile)
        g_m3kSrRollbackProfile = old;
    g_m3kSrProfileRequested = profile;
    g_m3kUqFallbackActive = false;
    g_m3kResolutionPlanProfile = 0xFFFFFFFFu;
    g_m3kResolutionPlanOutW = g_m3kResolutionPlanOutH = 0;
    g_m3kResolutionConfirmedLogged = false;
    g_m3kWasUsed = false;
'@
$vk = Replace-ExactOnce $vk $requestOld $requestNew 'live profile rollback/reset state'

# INI-driven requests get the same rollback/reset semantics as the ReShade control.
$pollOld = @'
            g_m3kSrProfileRequested = srProfile;
            g_m3kResolutionPlanProfile = 0xFFFFFFFFu;
            g_m3kResolutionPlanOutW = g_m3kResolutionPlanOutH = 0;
            g_m3kResolutionConfirmedLogged = false;
'@
$pollNew = @'
            if (g_m3kSrProfileApplied <= 5 && g_m3kSrProfileApplied != srProfile)
                g_m3kSrRollbackProfile = g_m3kSrProfileApplied;
            g_m3kSrProfileRequested = srProfile;
            g_m3kUqFallbackActive = false;
            g_m3kResolutionPlanProfile = 0xFFFFFFFFu;
            g_m3kResolutionPlanOutW = g_m3kResolutionPlanOutH = 0;
            g_m3kResolutionConfirmedLogged = false;
            g_m3kWasUsed = false;
'@
$vk = Replace-ExactOnce $vk $pollOld $pollNew 'INI profile rollback/reset state'

# Replace only S2.5's resolution-query helper. Official NGX sizing remains the first
# choice for every SR mode. Ultra Quality alone gets a deterministic 77% linear
# fallback when the query itself succeeds but returns zero dimensions.
$queryStart = $vk.IndexOf('static bool M3kQueryProfileRenderSize(', [StringComparison]::Ordinal)
$queryEnd = $vk.IndexOf('static bool M3kWriteRenderSizeIni(', $queryStart, [StringComparison]::Ordinal)
if ($queryStart -lt 0 -or $queryEnd -le $queryStart) { throw 'A2-S2.6 could not locate M3kQueryProfileRenderSize boundaries' }

$queryNew = @'
static bool M3kQueryProfileRenderSize(UINT profile, UINT targetW, UINT targetH, UINT *renderW, UINT *renderH)
{
    if (!renderW || !renderH || !targetW || !targetH) return false;
    g_m3kUqFallbackActive = false;

    if (profile == 0) {
        *renderW = targetW;
        *renderH = targetH;
        return true;
    }

    NVSDK_NGX_PerfQuality_Value q = NVSDK_NGX_PerfQuality_Value_MaxQuality;
    switch (profile) {
        case 1: q = NVSDK_NGX_PerfQuality_Value_UltraQuality; break;
        case 2: q = NVSDK_NGX_PerfQuality_Value_MaxQuality; break;
        case 3: q = NVSDK_NGX_PerfQuality_Value_Balanced; break;
        case 4: q = NVSDK_NGX_PerfQuality_Value_MaxPerf; break;
        case 5: q = NVSDK_NGX_PerfQuality_Value_UltraPerformance; break;
        default: return false;
    }

    NVSDK_NGX_Parameter *caps = nullptr;
    const NVSDK_NGX_Result cr = NVSDK_NGX_D3D12_GetCapabilityParameters(&caps);
    if (NVSDK_NGX_FAILED(cr) || caps == nullptr) {
        Log("M3K-RES-LIVE: %s resolution query failed: capability params 0x%08X", M3kSrProfileName(profile), cr);
        return false;
    }

    unsigned optW = 0, optH = 0, maxW = 0, maxH = 0, minW = 0, minH = 0;
    float sharp = 0.0f;
    const NVSDK_NGX_Result qr = NGX_DLSS_GET_OPTIMAL_SETTINGS(caps, targetW, targetH, q,
        &optW, &optH, &maxW, &maxH, &minW, &minH, &sharp);

    if (profile == 1 && NVSDK_NGX_SUCCEED(qr) && (!optW || !optH)) {
        // Experimental sizing fallback only. This is NOT claimed to be an official
        // NVIDIA Ultra Quality ratio. Actual UltraQuality feature creation remains
        // the runtime support gate.
        const UINT fallbackW = static_cast<UINT>((static_cast<UINT64>(targetW) * 77u + 50u) / 100u);
        const UINT fallbackH = static_cast<UINT>((static_cast<UINT64>(targetH) * 77u + 50u) / 100u);
        if (!fallbackW || !fallbackH) return false;
        *renderW = fallbackW;
        *renderH = fallbackH;
        g_m3kUqFallbackActive = true;
        Log("M3K-UQ: NGX query succeeded but returned 0x0 for %ux%u; using EXPERIMENTAL 77%% true-render fallback %ux%u, then attempting real UltraQuality feature creation",
            targetW, targetH, fallbackW, fallbackH);
        return true;
    }

    if (NVSDK_NGX_FAILED(qr) || !optW || !optH) {
        Log("M3K-RES-LIVE: %s has no NGX optimal render size for %ux%u result=0x%08X",
            M3kSrProfileName(profile), targetW, targetH, qr);
        return false;
    }

    *renderW = optW;
    *renderH = optH;
    if (profile == 1)
        Log("M3K-UQ: NGX supplied official-query true render=%ux%u for output=%ux%u allowed=%ux%u..%ux%u",
            optW, optH, targetW, targetH, minW, minH, maxW, maxH);
    else
        Log("M3K-RES-LIVE: %s optimal true render=%ux%u for output=%ux%u allowed=%ux%u..%ux%u",
            M3kSrProfileName(profile), optW, optH, targetW, targetH, minW, minH, maxW, maxH);
    return true;
}

'@
$vk = $vk.Substring(0, $queryStart) + $queryNew + $vk.Substring($queryEnd)

# S2.4 independently re-queries the selected DLSS mode before feature creation.
# Teach that gate to accept the already-planned UQ fallback only when the source
# exactly matches the planned fallback size. The DLSS feature itself still uses the
# genuine UltraQuality enum and preset hint.
$selectStart = $vk.IndexOf('static bool M3kSelectRequestedSrQuality(', [StringComparison]::Ordinal)
$selectEnd = $vk.IndexOf('static bool M3kSwapToSrFeature(', $selectStart, [StringComparison]::Ordinal)
if ($selectStart -lt 0 -or $selectEnd -le $selectStart) { throw 'A2-S2.6 could not locate M3kSelectRequestedSrQuality boundaries' }

$selectNew = @'
static bool M3kSelectRequestedSrQuality(UINT profile, UINT renderW, UINT renderH, UINT targetW, UINT targetH)
{
    if (profile < 1 || profile > 5) return false;
    struct Choice { NVSDK_NGX_PerfQuality_Value q; const char *name; const char *hint; };
    static const Choice choices[5] = {
        { NVSDK_NGX_PerfQuality_Value_UltraQuality,     "Ultra Quality",     NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_UltraQuality },
        { NVSDK_NGX_PerfQuality_Value_MaxQuality,       "Quality",           NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Quality },
        { NVSDK_NGX_PerfQuality_Value_Balanced,         "Balanced",          NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Balanced },
        { NVSDK_NGX_PerfQuality_Value_MaxPerf,          "Performance",       NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Performance },
        { NVSDK_NGX_PerfQuality_Value_UltraPerformance, "Ultra Performance", NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_UltraPerformance },
    };
    const Choice &c = choices[profile - 1];

    NVSDK_NGX_Parameter *caps = nullptr;
    const NVSDK_NGX_Result cr = NVSDK_NGX_D3D12_GetCapabilityParameters(&caps);
    if (NVSDK_NGX_FAILED(cr) || caps == nullptr) {
        Log("M3K-SR-LIVE: %s unavailable: GetCapabilityParameters failed 0x%08X", c.name, cr);
        return false;
    }

    unsigned optW = 0, optH = 0, maxW = 0, maxH = 0, minW = 0, minH = 0;
    float sharp = 0.0f;
    const NVSDK_NGX_Result qr = NGX_DLSS_GET_OPTIMAL_SETTINGS(caps, targetW, targetH, c.q,
        &optW, &optH, &maxW, &maxH, &minW, &minH, &sharp);

    const bool official = NVSDK_NGX_SUCCEED(qr) && optW != 0 && optH != 0;
    if (!official) {
        const bool uqFallback = profile == 1 && g_m3kUqFallbackActive && NVSDK_NGX_SUCCEED(qr) &&
            renderW == g_m3kDesiredRenderW && renderH == g_m3kDesiredRenderH;
        if (!uqFallback) {
            Log("M3K-SR-LIVE: %s not offered at %ux%u (0x%08X)", c.name, targetW, targetH, qr);
            return false;
        }
        Log("M3K-UQ: accepting EXPERIMENTAL fallback source %ux%u for actual UltraQuality create attempt; NGX sizing query still reports 0x0",
            renderW, renderH);
    } else {
        const bool inRange = renderW >= minW && renderW <= maxW && renderH >= minH && renderH <= maxH;
        Log("M3K-SR-LIVE: %s target=%ux%u optimal=%ux%u allowed=%ux%u..%ux%u true-source=%ux%u %s",
            c.name, targetW, targetH, optW, optH, minW, minH, maxW, maxH, renderW, renderH,
            inRange ? "ACCEPTED" : "OUT-OF-RANGE");
        if (!inRange) return false;
    }

    g.sr_quality = static_cast<int>(c.q);
    g.sr_quality_name = c.name;
    g.sr_quality_hint = c.hint;
    return true;
}

'@
$vk = $vk.Substring(0, $selectStart) + $selectNew + $vk.Substring($selectEnd)

# This is the core native-mode fix. S2.4 inserted a deliberate profile-0 early
# return after M3kSrUpdate(). Removing only that return reuses the proven A1 native
# path below: Feature18 runs first at g.width/g.height, then its output becomes the
# input color of the baseline DLAA feature.
$nativeBypass = @'
#if defined(VK_VERSION_1_0)
    if (g_m3kSrProfileRequested == 0) return;
#endif
'@
$vk = Replace-ExactOnce $vk $nativeBypass '' 'remove native NR bypass'

# If Ultra Quality feature creation rejects either official-query sizing or the
# experimental fallback after a resize, return to the profile that was stable before
# the request. This prevents the game remaining at an orphaned test resolution.
$createFailOld = @'
    if (!M3kSwapToSrFeature(info.width, info.height, info.presenterWidth, info.presenterHeight))
    {
        g_m3kSrLatchedFail = true;
        Log("M3K-SR-LIVE: initial SR create failed; toggle SRProfile or SRProof to retry");
    }
'@
$createFailNew = @'
    if (!M3kSwapToSrFeature(info.width, info.height, info.presenterWidth, info.presenterHeight))
    {
        const UINT failedProfile = g_m3kSrProfileRequested;
        if (failedProfile == 1)
        {
            UINT rollback = g_m3kSrRollbackProfile <= 5 ? g_m3kSrRollbackProfile : 2;
            if (rollback == 1) rollback = 2;
            Log("M3K-UQ: UltraQuality feature create failed (%s sizing); rolling back to %s and its true render resolution",
                g_m3kUqFallbackActive ? "experimental fallback" : "official-query", M3kSrProfileName(rollback));
            g_m3kSrProfileRequested = rollback;
            g_m3kUqFallbackActive = false;
            g_m3kResolutionPlanProfile = 0xFFFFFFFFu;
            g_m3kResolutionPlanOutW = g_m3kResolutionPlanOutH = 0;
            g_m3kResolutionConfirmedLogged = false;
            g_m3kSrLatchedFail = false;
            g_m3kWasUsed = false;
            g_m3k.ResetHistory();
            M3kWriteSrProfileIni(rollback);
            return;
        }
        g_m3kSrLatchedFail = true;
        Log("M3K-SR-LIVE: initial SR create failed; toggle SRProfile or SRProof to retry");
    }
'@
$vk = Replace-ExactOnce $vk $createFailOld $createFailNew 'UQ feature-create rollback'

# Expose truthful UQ fallback state to the ReShade panel.
$accessorOld = @'
static UINT M3kCurrentSourceHeight() { return g_m3kSourceTapReady ? g_m3kPresentSource.height : 0; }

static UINT M3kRequestedNrPasses() { return g_m3kNrPasses; }
'@
$accessorNew = @'
static UINT M3kCurrentSourceHeight() { return g_m3kSourceTapReady ? g_m3kPresentSource.height : 0; }
static bool M3kUqFallbackActive() { return g_m3kUqFallbackActive; }

static UINT M3kRequestedNrPasses() { return g_m3kNrPasses; }
'@
$vk = Replace-ExactOnce $vk $accessorOld $accessorNew 'UQ status accessor'

# Make the native proof explicit in logs instead of relying on the older generic
# A1 line. This fires only when Feature18 output actually fed the baseline DLAA.
$nativeLogOld = @'
    if (used && (++nrDlaaFrames == 1 || nrDlaaFrames % 300 == 0 || NVSDK_NGX_FAILED(result)))
        Log("M3K-A1: DLAA running after NR result=0x%08X reset=%d (same-frame guides retained)", result, dlaa.InReset);
'@
$nativeLogNew = @'
    if (used && (++nrDlaaFrames == 1 || nrDlaaFrames % 300 == 0 || NVSDK_NGX_FAILED(result)))
        Log("M3K-A2-S2.6: NR18 -> DLAA running %ux%u -> %ux%u result=0x%08X reset=%d mvScale=(%.3f,%.3f) jitter=(%.3f,%.3f)",
            g.width, g.height, g.width, g.height, result, dlaa.InReset,
            dlaa.InMVScaleX, dlaa.InMVScaleY, dlaa.InJitterOffsetX, dlaa.InJitterOffsetY);
'@
$vk = Replace-ExactOnce $vk $nativeLogOld $nativeLogNew 'native NR to DLAA runtime log'

# ReShade naming/status. Keep the permanent 1..5 NR selector untouched.
$feed = Replace-ExactOnce $feed `
    'DLAA native\\0Ultra Quality' `
    'Native + NR + DLAA\\0Ultra Quality' `
    'native combo label'

$overlayOld = @'
        if (M3kRequestedSrProfile() == 0)
            ImGui::TextWrapped("DLAA native requests the full presenter resolution as GTA's true render resolution, then uses DLAA without SR.");
        else
            ImGui::TextWrapped("Each DLSS mode requests NVIDIA's optimal input resolution, resizes GTA's true D3D9/DXVK source to it, then reconstructs to the native presenter.");
'@
$overlayNew = @'
        if (M3kRequestedSrProfile() == 0)
            ImGui::TextWrapped("Native + NR + DLAA requests the full presenter resolution as GTA's true render resolution, runs the selected 1-5 Feature18 NR passes at native size, then feeds NR output into DLAA.");
        else if (M3kRequestedSrProfile() == 1 && M3kUqFallbackActive())
            ImGui::TextWrapped("Ultra Quality sizing: NGX returned no optimal dimensions, so this run is using the experimental 77%% linear true-render fallback. The actual DLSS feature is still created with the UltraQuality enum; create failure rolls back safely.");
        else if (M3kRequestedSrProfile() == 1)
            ImGui::TextWrapped("Ultra Quality sizing: NGX supplied dimensions for this output; the actual DLSS feature uses the UltraQuality enum.");
        else
            ImGui::TextWrapped("Each DLSS mode requests NVIDIA's optimal input resolution, resizes GTA's true D3D9/DXVK source to it, then reconstructs to the native presenter.");
'@
$feed = Replace-ExactOnce $feed $overlayOld $overlayNew 'S2.6 ReShade status'

[IO.File]::WriteAllText($vkPath, $vk, (New-Object Text.UTF8Encoding($false)))
[IO.File]::WriteAllText($FeederSource, $feed, (New-Object Text.UTF8Encoding($false)))

$verify = $vk + $feed
foreach ($marker in @(
    'Native + NR + DLAA',
    'M3K-A2-S2.6: NR18 -> DLAA running',
    'M3K-UQ: NGX query succeeded but returned 0x0',
    'EXPERIMENTAL 77%% true-render fallback',
    'actual UltraQuality create attempt',
    'rolling back to %s and its true render resolution',
    'M3kUqFallbackActive()',
    'static constexpr unsigned MaxPasses = 5;')) {
    if ($verify.IndexOf($marker, [StringComparison]::Ordinal) -lt 0) {
        throw "A2-S2.6 verification marker missing: $marker"
    }
}

if ($vk.IndexOf('if (g_m3kSrProfileRequested == 0) return;', [StringComparison]::Ordinal) -ge 0) {
    throw 'A2-S2.6 verification failed: native NR bypass still present'
}

Write-Host "A2-S2.6 native NR + DLAA / UQ fallback source ready: $GeneratedRoot"
Write-Host 'Profile 0 now reuses the proven native Feature18 -> DLAA path; UQ fallback remains explicitly experimental.'
