# A2-S2.5 build-only transform: make the ReShade DLSS selector also change GTA's
# true D3D9/DXVK render resolution while keeping the presenter at native output.
# Input must already be generated by A2-S2.4.
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$GeneratedRoot,
    [Parameter(Mandatory=$true)][string]$FeederSource
)

$ErrorActionPreference = 'Stop'

function Replace-ExactOnce([string]$Text, [string]$Old, [string]$New, [string]$Label) {
    $count = 0
    $pos = 0
    while (($i = $Text.IndexOf($Old, $pos, [StringComparison]::Ordinal)) -ge 0) {
        $count++
        $pos = $i + $Old.Length
    }
    if ($count -ne 1) { throw "A2-S2.5 ${Label}: expected exactly one source match, found $count" }
    return $Text.Replace($Old, $New)
}

$vkPath = Join-Path $GeneratedRoot 'm3k_vk.h'
if (-not (Test-Path -LiteralPath $vkPath)) { throw "Missing generated m3k_vk.h under $GeneratedRoot" }
if (-not (Test-Path -LiteralPath $FeederSource)) { throw "Missing Feeder source: $FeederSource" }

$vk = [IO.File]::ReadAllText($vkPath)
$feed = [IO.File]::ReadAllText($FeederSource)

# Resolution-plan state lives beside the S2.4 live SR profile state.
$stateOld = @'
static UINT g_m3kSrProfileRequested = 2; // Quality
static UINT g_m3kSrProfileApplied = 0xFFFFFFFFu;
'@
$stateNew = @'
static UINT g_m3kSrProfileRequested = 2; // Quality
static UINT g_m3kSrProfileApplied = 0xFFFFFFFFu;
static UINT g_m3kDesiredRenderW = 0, g_m3kDesiredRenderH = 0;
static UINT g_m3kResolutionPlanProfile = 0xFFFFFFFFu;
static UINT g_m3kResolutionPlanOutW = 0, g_m3kResolutionPlanOutH = 0;
static ULONGLONG g_m3kNextResizeSignal = 0;
static UINT g_m3kResizeSignalAttempts = 0;
static bool g_m3kResolutionConfirmedLogged = false;
'@
$vk = Replace-ExactOnce $vk $stateOld $stateNew 'resolution state'

# DLAA is now a real native-render profile rather than a presenter-only baseline.
$vk = $vk.Replace('case 0: return "DLAA only (presenter)";', 'case 0: return "DLAA native";')

# A new profile selection invalidates the resolution plan. The normal render path
# will query NGX optimal settings, write RenderWidth/Height, then signal GTA's window.
$requestOld = @'
    const UINT old = g_m3kSrProfileRequested;
    g_m3kSrProfileRequested = profile;
#if defined(VK_VERSION_1_0)
'@
$requestNew = @'
    const UINT old = g_m3kSrProfileRequested;
    g_m3kSrProfileRequested = profile;
    g_m3kResolutionPlanProfile = 0xFFFFFFFFu;
    g_m3kResolutionPlanOutW = g_m3kResolutionPlanOutH = 0;
    g_m3kResolutionConfirmedLogged = false;
#if defined(VK_VERSION_1_0)
'@
$vk = Replace-ExactOnce $vk $requestOld $requestNew 'live request invalidates resolution plan'
$vk = $vk.Replace('M3K-SR-LIVE: ReShade requested reconstruction %s -> %s; applies on next frame',
                  'M3K-SR-LIVE: ReShade requested reconstruction %s -> %s; planning matching true render resolution')

$accessorAnchor = 'static UINT M3kRequestedNrPasses() { return g_m3kNrPasses; }'
$helpers = @'
static bool M3kQueryProfileRenderSize(UINT profile, UINT targetW, UINT targetH, UINT *renderW, UINT *renderH)
{
    if (!renderW || !renderH || !targetW || !targetH) return false;
    if (profile == 0) {
        *renderW = targetW;
        *renderH = targetH;
        return true;
    }

    NVSDK_NGX_PerfQuality_Value q = NVSDK_NGX_PerfQuality_Value_MaxQuality;
    switch (profile) {
        case 1: q = NVSDK_NGX_PerfQuality_Value_UltraQuality; break;
        case 2: q = NVSDK_NGX_PerfQuality_Value_MaxQuality; break;
        case 3: q = NVSDK_NGX_PerfQuality_Value_Balanced; break;
        case 4: q = NVSDK_NGX_PerfQuality_Value_MaxPerf; break;
        case 5: q = NVSDK_NGX_PerfQuality_Value_UltraPerformance; break;
        default: return false;
    }

    NVSDK_NGX_Parameter *caps = nullptr;
    const NVSDK_NGX_Result cr = NVSDK_NGX_D3D12_GetCapabilityParameters(&caps);
    if (NVSDK_NGX_FAILED(cr) || caps == nullptr) {
        Log("M3K-RES-LIVE: %s resolution query failed: capability params 0x%08X", M3kSrProfileName(profile), cr);
        return false;
    }

    unsigned optW = 0, optH = 0, maxW = 0, maxH = 0, minW = 0, minH = 0;
    float sharp = 0.0f;
    const NVSDK_NGX_Result qr = NGX_DLSS_GET_OPTIMAL_SETTINGS(caps, targetW, targetH, q,
        &optW, &optH, &maxW, &maxH, &minW, &minH, &sharp);
    if (NVSDK_NGX_FAILED(qr) || !optW || !optH) {
        Log("M3K-RES-LIVE: %s has no NGX optimal render size for %ux%u result=0x%08X",
            M3kSrProfileName(profile), targetW, targetH, qr);
        return false;
    }

    *renderW = optW;
    *renderH = optH;
    Log("M3K-RES-LIVE: %s optimal true render=%ux%u for output=%ux%u allowed=%ux%u..%ux%u",
        M3kSrProfileName(profile), optW, optH, targetW, targetH, minW, minH, maxW, maxH);
    return true;
}

static bool M3kWriteRenderSizeIni(UINT width, UINT height)
{
    wchar_t path[MAX_PATH] = {};
    if (!GetModuleFileNameW(g_self, path, MAX_PATH)) return false;
    wchar_t *slash = wcsrchr(path, L'\\');
    if (!slash) return false;
    *(slash + 1) = 0;
    wcscat_s(path, L"m3k-nr.ini");

    wchar_t w[16] = {}, h[16] = {};
    _snwprintf_s(w, _TRUNCATE, L"%u", width);
    _snwprintf_s(h, _TRUNCATE, L"%u", height);
    const BOOL okW = WritePrivateProfileStringW(L"M3K", L"RenderWidth", w, path);
    const BOOL okH = WritePrivateProfileStringW(L"M3K", L"RenderHeight", h, path);
    WritePrivateProfileStringW(L"M3K", L"VirtualizeGameClient", L"1", path);
    WritePrivateProfileStringW(L"M3K", L"AutoResizeWindow", L"1", path);
    return okW && okH;
}

static bool M3kSignalGtaResize(UINT width, UINT height)
{
    HWND hwnd = FindWindowW(L"grcWindow", nullptr);
    if (!hwnd) {
        Log("M3K-RES-LIVE: GTA grcWindow not found; resize signal deferred");
        return false;
    }

    const LPARAM size = MAKELPARAM(width & 0xFFFFu, height & 0xFFFFu);
    const BOOL posted = PostMessageW(hwnd, WM_SIZE, SIZE_RESTORED, size);
    PostMessageW(hwnd, WM_EXITSIZEMOVE, 0, 0);
    Log("M3K-RES-LIVE: posted logical WM_SIZE %ux%u to GTA hwnd=0x%p result=%d",
        width, height, hwnd, posted ? 1 : 0);
    return posted != FALSE;
}

static void M3kSyncRequestedRenderResolution()
{
    if (!g.width || !g.height) return;

    if (g_m3kResolutionPlanProfile != g_m3kSrProfileRequested ||
        g_m3kResolutionPlanOutW != g.width || g_m3kResolutionPlanOutH != g.height) {
        UINT wantedW = 0, wantedH = 0;
        if (!M3kQueryProfileRenderSize(g_m3kSrProfileRequested, g.width, g.height, &wantedW, &wantedH)) {
            const UINT fallback = g_m3kSrProfileApplied <= 5 ? g_m3kSrProfileApplied : 2;
            Log("M3K-RES-LIVE: rejecting %s because its true render size could not be resolved; restoring %s",
                M3kSrProfileName(g_m3kSrProfileRequested), M3kSrProfileName(fallback));
            g_m3kSrProfileRequested = fallback;
            M3kWriteSrProfileIni(fallback);
            g_m3kResolutionPlanProfile = 0xFFFFFFFFu;
            return;
        }

        g_m3kDesiredRenderW = wantedW;
        g_m3kDesiredRenderH = wantedH;
        g_m3kResolutionPlanProfile = g_m3kSrProfileRequested;
        g_m3kResolutionPlanOutW = g.width;
        g_m3kResolutionPlanOutH = g.height;
        g_m3kNextResizeSignal = 0;
        g_m3kResizeSignalAttempts = 0;
        g_m3kResolutionConfirmedLogged = false;

        if (!M3kWriteRenderSizeIni(wantedW, wantedH))
            Log("M3K-RES-LIVE: WARNING could not persist RenderWidth/RenderHeight=%ux%u", wantedW, wantedH);
        else
            Log("M3K-RES-LIVE: profile %s requests TRUE GTA render %ux%u -> presenter %ux%u",
                M3kSrProfileName(g_m3kSrProfileRequested), wantedW, wantedH, g.width, g.height);
    }

    if (!g_m3kSourceTapReady || !g_m3kDesiredRenderW || !g_m3kDesiredRenderH) return;

    if (g_m3kPresentSource.width == g_m3kDesiredRenderW &&
        g_m3kPresentSource.height == g_m3kDesiredRenderH) {
        if (!g_m3kResolutionConfirmedLogged) {
            g_m3kResolutionConfirmedLogged = true;
            Log("M3K-RES-LIVE: TRUE source confirmed %ux%u for %s; presenter remains %ux%u",
                g_m3kPresentSource.width, g_m3kPresentSource.height,
                M3kSrProfileName(g_m3kSrProfileRequested),
                g_m3kPresentSource.presenterWidth, g_m3kPresentSource.presenterHeight);
        }
        return;
    }

    const ULONGLONG now = GetTickCount64();
    if (now < g_m3kNextResizeSignal) return;
    g_m3kNextResizeSignal = now + 1200;
    ++g_m3kResizeSignalAttempts;
    M3kSignalGtaResize(g_m3kDesiredRenderW, g_m3kDesiredRenderH);
    Log("M3K-RES-LIVE: waiting for DXVK source %ux%u -> %ux%u (signal attempt %u)",
        g_m3kPresentSource.width, g_m3kPresentSource.height,
        g_m3kDesiredRenderW, g_m3kDesiredRenderH, g_m3kResizeSignalAttempts);
}

static UINT M3kDesiredRenderWidth() { return g_m3kDesiredRenderW; }
static UINT M3kDesiredRenderHeight() { return g_m3kDesiredRenderH; }
static UINT M3kCurrentSourceWidth() { return g_m3kSourceTapReady ? g_m3kPresentSource.width : 0; }
static UINT M3kCurrentSourceHeight() { return g_m3kSourceTapReady ? g_m3kPresentSource.height : 0; }

static UINT M3kRequestedNrPasses() { return g_m3kNrPasses; }
'@
$vk = Replace-ExactOnce $vk $accessorAnchor $helpers 'dynamic-resolution helpers'

# INI polling can also change SRProfile; invalidate the resolution plan there too.
$pollOld = @'
            g_m3kSrProfileRequested = srProfile;
#if defined(VK_VERSION_1_0)
'@
$pollNew = @'
            g_m3kSrProfileRequested = srProfile;
            g_m3kResolutionPlanProfile = 0xFFFFFFFFu;
            g_m3kResolutionPlanOutW = g_m3kResolutionPlanOutH = 0;
            g_m3kResolutionConfirmedLogged = false;
#if defined(VK_VERSION_1_0)
'@
$vk = Replace-ExactOnce $vk $pollOld $pollNew 'INI profile resolution invalidation'

# Let the resolution planner run on the normal frame path, then let SR react only
# after DXVK's source tap proves that the true source has actually changed.
$prepareOld = @'
    M3kProbeDxvkPresentSource();
#if defined(VK_VERSION_1_0)
    M3kSrUpdate();
#endif
'@
$prepareNew = @'
    M3kProbeDxvkPresentSource();
#if defined(VK_VERSION_1_0)
    M3kSyncRequestedRenderResolution();
    M3kSrUpdate();
#endif
'@
$vk = Replace-ExactOnce $vk $prepareOld $prepareNew 'resolution sync before SR update'

# Profile 0 waits for a true native source before restoring DLAA.
$dlaaOld = @'
    if (g_m3kSrProfileRequested == 0)
    {
        if (g_m3kSrFeatureActive) M3kRestoreDlaaFeature();
        else g_m3kSrProfileApplied = 0;
        return;
    }
'@
$dlaaNew = @'
    if (g_m3kSrProfileRequested == 0)
    {
        if (g_m3kDesiredRenderW && g_m3kDesiredRenderH &&
            (!g_m3kSourceTapReady || g_m3kPresentSource.width != g_m3kDesiredRenderW ||
             g_m3kPresentSource.height != g_m3kDesiredRenderH))
            return;
        if (g_m3kSrFeatureActive) M3kRestoreDlaaFeature();
        else g_m3kSrProfileApplied = 0;
        return;
    }
'@
$vk = Replace-ExactOnce $vk $dlaaOld $dlaaNew 'native DLAA waits for source resize'

# SR profiles likewise wait for the matching true source instead of rebuilding a
# new quality mode against the previous profile's render extent.
$infoAnchor = @'
    const auto &info = g_m3kPresentSource;
    const bool split = info.presenterWidth == g.width && info.presenterHeight == g.height &&
'@
$infoNew = @'
    const auto &info = g_m3kPresentSource;
    if (g_m3kDesiredRenderW && g_m3kDesiredRenderH &&
        (info.width != g_m3kDesiredRenderW || info.height != g_m3kDesiredRenderH))
        return;
    const bool split = info.presenterWidth == g.width && info.presenterHeight == g.height &&
'@
$vk = Replace-ExactOnce $vk $infoAnchor $infoNew 'SR waits for desired true source'

# ReShade should show the actual true render target/current source, not claim that
# all quality levels use a fixed 1600x900 source.
$feed = $feed.Replace('DLAA only (presenter)\\0Ultra Quality', 'DLAA native\\0Ultra Quality')
$overlayOld = @'
        ImGui::Text("Applied: %s", M3kSrProfileName(M3kAppliedSrProfile()));
        if (M3kRequestedSrProfile() == 0)
            ImGui::TextWrapped("DLAA-only is a presenter-space A/B baseline. GTA's true S1B render remains 1600x900; it is not native-rendered 1440p DLAA.");
        else
            ImGui::TextWrapped("SR profiles keep the true DXVK source resolution fixed and change NVIDIA's DLSS perf-quality profile. Unsupported profiles at this input size are rejected safely.");
'@
$overlayNew = @'
        ImGui::Text("Applied: %s", M3kSrProfileName(M3kAppliedSrProfile()));
        ImGui::Text("True render target: %u x %u", M3kDesiredRenderWidth(), M3kDesiredRenderHeight());
        ImGui::Text("DXVK source now:    %u x %u", M3kCurrentSourceWidth(), M3kCurrentSourceHeight());
        if (M3kDesiredRenderWidth() != M3kCurrentSourceWidth() || M3kDesiredRenderHeight() != M3kCurrentSourceHeight())
            ImGui::TextColored(ImVec4(1.0f, 0.78f, 0.25f, 1.0f), "Applying GTA/DXVK render resize...");
        if (M3kRequestedSrProfile() == 0)
            ImGui::TextWrapped("DLAA native requests the full presenter resolution as GTA's true render resolution, then uses DLAA without SR.");
        else
            ImGui::TextWrapped("Each DLSS mode requests NVIDIA's optimal input resolution, resizes GTA's true D3D9/DXVK source to it, then reconstructs to the native presenter.");
'@
$feed = Replace-ExactOnce $feed $overlayOld $overlayNew 'dynamic-resolution ReShade status'

[IO.File]::WriteAllText($vkPath, $vk, (New-Object Text.UTF8Encoding($false)))
[IO.File]::WriteAllText($FeederSource, $feed, (New-Object Text.UTF8Encoding($false)))

$verify = $vk + $feed
foreach ($marker in @(
    'M3K-RES-LIVE: profile %s requests TRUE GTA render',
    'M3K-RES-LIVE: TRUE source confirmed',
    'FindWindowW(L"grcWindow"',
    'M3kSyncRequestedRenderResolution',
    'True render target:',
    'DLAA native')) {
    if ($verify.IndexOf($marker, [StringComparison]::Ordinal) -lt 0) {
        throw "A2-S2.5 verification marker missing: $marker"
    }
}

Write-Host "A2-S2.5 dynamic-resolution source ready: $GeneratedRoot"
Write-Host 'ReShade DLSS profile now drives true GTA/DXVK render resolution.'
