# A3-S3 diagnostic-only transform: split Balanced's render size from its NGX contract.
# Input must already be generated by A3-S1.2. This patch changes ONLY SR feature
# selection for two explicit probe states read from m3k-nr.ini:
#   BalancedProbe=1 -> profile 3 keeps Balanced resolution, but creates MaxQuality/Quality contract.
#   BalancedProbe=2 -> profile 2 keeps Quality resolution, but creates Balanced contract.
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$GeneratedRoot
)
$ErrorActionPreference = 'Stop'

function Replace-ExactOnce([string]$Text,[string]$Old,[string]$New,[string]$Label) {
    $count=0; $pos=0
    while (($i=$Text.IndexOf($Old,$pos,[StringComparison]::Ordinal)) -ge 0) { $count++; $pos=$i+$Old.Length }
    if ($count -ne 1) { throw "A3-S3 ${Label}: expected exactly one source match, found $count" }
    return $Text.Replace($Old,$New)
}

$vkPath = Join-Path $GeneratedRoot 'm3k_vk.h'
if (-not (Test-Path -LiteralPath $vkPath)) { throw "Missing generated m3k_vk.h: $vkPath" }
$vk = [IO.File]::ReadAllText($vkPath)

$selectorAnchor = 'static bool M3kSelectRequestedSrQuality(UINT profile, UINT renderW, UINT renderH, UINT targetW, UINT targetH)'
$helper = @'
static UINT M3kBalancedProbeMode()
{
    wchar_t path[MAX_PATH] = {};
    if (!GetModuleFileNameW(g_self, path, MAX_PATH)) return 0;
    wchar_t *slash = wcsrchr(path, L'\\');
    if (!slash) return 0;
    *(slash + 1) = 0;
    wcscat_s(path, L"m3k-nr.ini");
    const UINT v = GetPrivateProfileIntW(L"M3K", L"BalancedProbe", 0, path);
    return v <= 2 ? v : 0;
}

static bool M3kSelectRequestedSrQuality(UINT profile, UINT renderW, UINT renderH, UINT targetW, UINT targetH)
'@
$vk = Replace-ExactOnce $vk $selectorAnchor $helper 'probe helper injection'

$choiceOld = @'
    const Choice &c = choices[profile - 1];

    NVSDK_NGX_Parameter *caps = nullptr;
'@
$choiceNew = @'
    Choice c = choices[profile - 1];
    const UINT balancedProbe = M3kBalancedProbeMode();
    if (balancedProbe == 1 && profile == 3) {
        // Keep profile-3's Balanced-derived 1485x835 resolution plan, but use the
        // supported MaxQuality/Quality feature contract. This isolates resolution.
        c.q = NVSDK_NGX_PerfQuality_Value_MaxQuality;
        c.name = "PROBE A: Balanced resolution + Quality contract";
        c.hint = NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Quality;
        Log("M3K-A3-S3: PROBE A active: Balanced resolution with Quality/MaxQuality NGX contract");
    } else if (balancedProbe == 2 && profile == 2) {
        // Keep profile-2's Quality-derived resolution plan, but use the supported
        // Balanced feature contract. This isolates the NGX perf-quality/preset state.
        c.q = NVSDK_NGX_PerfQuality_Value_Balanced;
        c.name = "PROBE B: Quality resolution + Balanced contract";
        c.hint = NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Balanced;
        Log("M3K-A3-S3: PROBE B active: Quality resolution with Balanced NGX contract");
    }

    NVSDK_NGX_Parameter *caps = nullptr;
'@
$vk = Replace-ExactOnce $vk $choiceOld $choiceNew 'hybrid contract override'

[IO.File]::WriteAllText($vkPath,$vk,[Text.UTF8Encoding]::new($false))
Write-Host 'A3-S3 Balanced isolation probe applied.'
