# A3-S5 production-candidate transform: automatically prime GTA/DXVK/Feeder at the
# empirically stable 1485x835 source size, then return to the user's saved SRProfile.
# Input must already be generated by A3-S4. A3-S2 bridge/jitter math is untouched.
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$GeneratedRoot
)
$ErrorActionPreference = 'Stop'

function Replace-ExactOnce([string]$Text,[string]$Old,[string]$New,[string]$Label) {
    $count=0; $pos=0
    while (($i=$Text.IndexOf($Old,$pos,[StringComparison]::Ordinal)) -ge 0) { $count++; $pos=$i+$Old.Length }
    if ($count -ne 1) { throw "A3-S5 ${Label}: expected exactly one source match, found $count" }
    return $Text.Replace($Old,$New)
}

$vkPath = Join-Path $GeneratedRoot 'm3k_vk.h'
if (-not (Test-Path -LiteralPath $vkPath)) { throw "Missing generated m3k_vk.h: $vkPath" }
$vk = [IO.File]::ReadAllText($vkPath)

$stateOld = 'static bool g_m3kResolutionConfirmedLogged = false;'
$stateNew = @'
static bool g_m3kResolutionConfirmedLogged = false;

// A3-S5 startup primer. Hardware tests found a narrow stable source-size band:
// 1478x832 and 1485x835 cure the cold-start vibration while 1472x828 and
// 1493x840 do not. Hold the pipeline at 1485x835 with a supported Quality
// contract until the exact A3-S2 raster/DLSS jitter handoff is live and stable,
// then invalidate the resolution plan so the already-requested/saved SRProfile
// takes over normally. No projection/jitter math is changed here.
static bool g_m3kStartupPrimeConfigured = false;
static bool g_m3kStartupPrimeEnabled = false;
static bool g_m3kStartupPrimeActive = false;
static bool g_m3kStartupPrimeCompleted = false;
static UINT g_m3kStartupPrimeW = 1485;
static UINT g_m3kStartupPrimeH = 835;
static UINT g_m3kStartupPrimeRequiredFrames = 180;
static UINT g_m3kStartupPrimeStableFrames = 0;
static LONG g_m3kStartupPrimeEpoch = -1;
'@
$vk = Replace-ExactOnce $vk $stateOld $stateNew 'startup-prime state'

$manualAnchor = 'static bool M3kReadManualRenderSize(UINT *manualW, UINT *manualH)'
$primeHelpers = @'
static void M3kStartupPrimeConfigure(UINT targetW, UINT targetH)
{
    if (g_m3kStartupPrimeConfigured) return;
    g_m3kStartupPrimeConfigured = true;

    wchar_t path[MAX_PATH] = {};
    if (!GetModuleFileNameW(g_self, path, MAX_PATH)) return;
    wchar_t *slash = wcsrchr(path, L'\\');
    if (!slash) return;
    *(slash + 1) = 0;
    wcscat_s(path, L"m3k-nr.ini");

    g_m3kStartupPrimeEnabled = GetPrivateProfileIntW(L"M3K", L"StartupPrime", 1, path) != 0;
    const UINT cfgW = GetPrivateProfileIntW(L"M3K", L"StartupPrimeWidth", 1485, path);
    const UINT cfgH = GetPrivateProfileIntW(L"M3K", L"StartupPrimeHeight", 835, path);
    const UINT cfgFrames = GetPrivateProfileIntW(L"M3K", L"StartupPrimeFrames", 180, path);
    if (cfgW >= 320 && cfgH >= 180 && cfgW <= 4096 && cfgH <= 4096) {
        g_m3kStartupPrimeW = cfgW;
        g_m3kStartupPrimeH = cfgH;
    }
    g_m3kStartupPrimeRequiredFrames = cfgFrames < 30 ? 30 : (cfgFrames > 1200 ? 1200 : cfgFrames);

    // Prime only reconstruction profiles. Native/DLAA has no low-source startup problem.
    if (!g_m3kStartupPrimeEnabled || g_m3kSrProfileRequested < 1 || g_m3kSrProfileRequested > 5) {
        Log("M3K-A3-S5: startup prime disabled/not applicable; requested=%s",
            M3kSrProfileName(g_m3kSrProfileRequested));
        return;
    }
    if (targetW < g_m3kStartupPrimeW || targetH < g_m3kStartupPrimeH) {
        Log("M3K-A3-S5: startup prime skipped: output %ux%u smaller than prime %ux%u",
            targetW, targetH, g_m3kStartupPrimeW, g_m3kStartupPrimeH);
        return;
    }

    g_m3kStartupPrimeActive = true;
    g_m3kStartupPrimeCompleted = false;
    g_m3kStartupPrimeStableFrames = 0;
    g_m3kStartupPrimeEpoch = -1;
    Log("M3K-A3-S5: STARTUP PRIME armed %ux%u, hold=%u synchronized SR frames, saved request=%s",
        g_m3kStartupPrimeW, g_m3kStartupPrimeH, g_m3kStartupPrimeRequiredFrames,
        M3kSrProfileName(g_m3kSrProfileRequested));
}

static void M3kStartupPrimeObserve(bool bridgeJitterActive, LONG bridgeEpoch, UINT renderW, UINT renderH)
{
    if (!g_m3kStartupPrimeActive) return;
    if (!bridgeJitterActive || renderW != g_m3kStartupPrimeW || renderH != g_m3kStartupPrimeH) {
        g_m3kStartupPrimeStableFrames = 0;
        g_m3kStartupPrimeEpoch = -1;
        return;
    }

    if (g_m3kStartupPrimeEpoch != bridgeEpoch) {
        g_m3kStartupPrimeEpoch = bridgeEpoch;
        g_m3kStartupPrimeStableFrames = 0;
        Log("M3K-A3-S5: prime synchronized to A3-S2 jitter epoch=%ld at %ux%u",
            bridgeEpoch, renderW, renderH);
    }

    ++g_m3kStartupPrimeStableFrames;
    if (g_m3kStartupPrimeStableFrames < g_m3kStartupPrimeRequiredFrames) return;

    g_m3kStartupPrimeActive = false;
    g_m3kStartupPrimeCompleted = true;
    g_m3kResolutionPlanProfile = 0xFFFFFFFFu;
    g_m3kResolutionPlanOutW = g_m3kResolutionPlanOutH = 0;
    g_m3kResolutionConfirmedLogged = false;
    g_m3kSrNeedsReset = true;
    g_m3kWasUsed = false;
    g_m3k.ResetHistory();
    Log("M3K-A3-S5: STARTUP PRIME COMPLETE after %u synchronized SR frames; releasing to saved %s",
        g_m3kStartupPrimeStableFrames, M3kSrProfileName(g_m3kSrProfileRequested));
}

static bool M3kReadManualRenderSize(UINT *manualW, UINT *manualH)
'@
$vk = Replace-ExactOnce $vk $manualAnchor $primeHelpers 'startup-prime helpers'

$queryOld = @'
static bool M3kQueryProfileRenderSize(UINT profile, UINT targetW, UINT targetH, UINT *renderW, UINT *renderH)
{
    if (!renderW || !renderH || !targetW || !targetH) return false;
    UINT manualW = 0, manualH = 0;
'@
$queryNew = @'
static bool M3kQueryProfileRenderSize(UINT profile, UINT targetW, UINT targetH, UINT *renderW, UINT *renderH)
{
    if (!renderW || !renderH || !targetW || !targetH) return false;
    M3kStartupPrimeConfigure(targetW, targetH);
    if (g_m3kStartupPrimeActive) {
        g_m3kUqFallbackActive = false;
        *renderW = g_m3kStartupPrimeW;
        *renderH = g_m3kStartupPrimeH;
        Log("M3K-A3-S5: startup prime requests TRUE GTA render %ux%u -> presenter %ux%u",
            *renderW, *renderH, targetW, targetH);
        return true;
    }
    UINT manualW = 0, manualH = 0;
'@
$vk = Replace-ExactOnce $vk $queryOld $queryNew 'prime render-size override'

$choiceOld = @'
    } else if (balancedProbe == 2 && profile == 2) {
        // Keep profile-2's Quality-derived resolution plan, but use the supported
        // Balanced feature contract. This isolates the NGX perf-quality/preset state.
        c.q = NVSDK_NGX_PerfQuality_Value_Balanced;
        c.name = "PROBE B: Quality resolution + Balanced contract";
        c.hint = NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Balanced;
        Log("M3K-A3-S3: PROBE B active: Quality resolution with Balanced NGX contract");
    }

    NVSDK_NGX_Parameter *caps = nullptr;
'@
$choiceNew = @'
    } else if (balancedProbe == 2 && profile == 2) {
        // Keep profile-2's Quality-derived resolution plan, but use the supported
        // Balanced feature contract. This isolates the NGX perf-quality/preset state.
        c.q = NVSDK_NGX_PerfQuality_Value_Balanced;
        c.name = "PROBE B: Quality resolution + Balanced contract";
        c.hint = NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Balanced;
        Log("M3K-A3-S3: PROBE B active: Quality resolution with Balanced NGX contract");
    }
    if (g_m3kStartupPrimeActive) {
        c = choices[1]; // supported Quality / MaxQuality contract at the known-good source size
        c.name = "STARTUP PRIME: Quality contract";
        c.hint = NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Quality;
    }

    NVSDK_NGX_Parameter *caps = nullptr;
'@
$vk = Replace-ExactOnce $vk $choiceOld $choiceNew 'prime Quality contract'

$observeOld = '        g_m3kJitterLastFrame = bridgeJitterActive ? bridgeJitter.frame : -1;'
$observeNew = @'
        g_m3kJitterLastFrame = bridgeJitterActive ? bridgeJitter.frame : -1;
        M3kStartupPrimeObserve(bridgeJitterActive,
            bridgeJitterActive ? bridgeJitter.epoch : -1,
            g_m3kSrW, g_m3kSrH);
'@
$vk = Replace-ExactOnce $vk $observeOld $observeNew 'prime synchronized-frame observer'

foreach ($marker in @(
    'M3K-A3-S5: STARTUP PRIME armed',
    'M3K-A3-S5: prime synchronized to A3-S2 jitter epoch=',
    'M3K-A3-S5: STARTUP PRIME COMPLETE',
    'STARTUP PRIME: Quality contract',
    'StartupPrimeWidth',
    'M3kStartupPrimeObserve(bridgeJitterActive')) {
    if ($vk.IndexOf($marker,[StringComparison]::Ordinal) -lt 0) { throw "Generated A3-S5 source missing marker: $marker" }
}

[IO.File]::WriteAllText($vkPath,$vk,[Text.UTF8Encoding]::new($false))
Write-Host 'A3-S5 automatic startup-prime candidate applied.'