# A3-S4 diagnostic-only transform: allow arbitrary true source resolutions while
# keeping the DLSS reconstruction contract fixed to profile 2 (Quality/MaxQuality).
# Input must already be generated by A3-S3.
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$GeneratedRoot
)
$ErrorActionPreference = 'Stop'

function Replace-ExactOnce([string]$Text,[string]$Old,[string]$New,[string]$Label) {
    $count=0; $pos=0
    while (($i=$Text.IndexOf($Old,$pos,[StringComparison]::Ordinal)) -ge 0) { $count++; $pos=$i+$Old.Length }
    if ($count -ne 1) { throw "A3-S4 ${Label}: expected exactly one source match, found $count" }
    return $Text.Replace($Old,$New)
}

$vkPath = Join-Path $GeneratedRoot 'm3k_vk.h'
if (-not (Test-Path -LiteralPath $vkPath)) { throw "Missing generated m3k_vk.h: $vkPath" }
$vk = [IO.File]::ReadAllText($vkPath)

$queryAnchor = @'
static bool M3kQueryProfileRenderSize(UINT profile, UINT targetW, UINT targetH, UINT *renderW, UINT *renderH)
{
    if (!renderW || !renderH || !targetW || !targetH) return false;
'@
$queryNew = @'
static bool M3kReadManualRenderSize(UINT *manualW, UINT *manualH)
{
    if (!manualW || !manualH) return false;
    *manualW = *manualH = 0;
    wchar_t path[MAX_PATH] = {};
    if (!GetModuleFileNameW(g_self, path, MAX_PATH)) return false;
    wchar_t *slash = wcsrchr(path, L'\\');
    if (!slash) return false;
    *(slash + 1) = 0;
    wcscat_s(path, L"m3k-nr.ini");
    const UINT enabled = GetPrivateProfileIntW(L"M3K", L"ManualRender", 0, path);
    if (!enabled) return false;
    const UINT w = GetPrivateProfileIntW(L"M3K", L"ManualRenderWidth", 0, path);
    const UINT h = GetPrivateProfileIntW(L"M3K", L"ManualRenderHeight", 0, path);
    if (w < 320 || h < 180 || w > 4096 || h > 4096) return false;
    *manualW = w; *manualH = h;
    return true;
}

static bool M3kQueryProfileRenderSize(UINT profile, UINT targetW, UINT targetH, UINT *renderW, UINT *renderH)
{
    if (!renderW || !renderH || !targetW || !targetH) return false;
    UINT manualW = 0, manualH = 0;
    if (profile == 2 && M3kReadManualRenderSize(&manualW, &manualH)) {
        *renderW = manualW;
        *renderH = manualH;
        Log("M3K-A3-S4: manual Quality source requested %ux%u for output=%ux%u",
            manualW, manualH, targetW, targetH);
        return true;
    }
'@
$vk = Replace-ExactOnce $vk $queryAnchor $queryNew 'manual query override'

$syncAnchor = @'
static void M3kSyncRequestedRenderResolution()
{
    if (!g.width || !g.height) return;

    if (g_m3kResolutionPlanProfile != g_m3kSrProfileRequested ||
'@
$syncNew = @'
static void M3kSyncRequestedRenderResolution()
{
    if (!g.width || !g.height) return;

    // Live manual-resolution changes must invalidate the cached plan even when
    // SRProfile remains fixed at Quality. This lets the BAT change only dimensions.
    static UINT lastManualW = 0, lastManualH = 0;
    static bool lastManualActive = false;
    UINT manualW = 0, manualH = 0;
    const bool manualActive = (g_m3kSrProfileRequested == 2) && M3kReadManualRenderSize(&manualW, &manualH);
    if (manualActive != lastManualActive || manualW != lastManualW || manualH != lastManualH) {
        lastManualActive = manualActive;
        lastManualW = manualW;
        lastManualH = manualH;
        g_m3kResolutionPlanProfile = 0xFFFFFFFFu;
        g_m3kResolutionPlanOutW = g_m3kResolutionPlanOutH = 0;
        g_m3kResolutionConfirmedLogged = false;
        g_m3kSrNeedsReset = true;
        g_m3k.ResetHistory();
        Log("M3K-A3-S4: manual source state changed active=%u size=%ux%u; resolution plan invalidated",
            manualActive ? 1u : 0u, manualW, manualH);
    }

    if (g_m3kResolutionPlanProfile != g_m3kSrProfileRequested ||
'@
$vk = Replace-ExactOnce $vk $syncAnchor $syncNew 'live manual invalidation'

[IO.File]::WriteAllText($vkPath,$vk,[Text.UTF8Encoding]::new($false))
Write-Host 'A3-S4 manual-resolution diagnostic hook applied.'
